name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:bookworm #aiarena/arenaclient
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: apt-get update && apt-get upgrade --assume-yes --quiet=2 && apt-get install --assume-yes --no-install-recommends --no-show-upgraded cmake gnupg2 wget make git procps g++ ffmpeg libsm6 libxext6 unzip && rm -rf /var/lib/apt/lists/* && wget https://letsencrypt.org/certs/isrg-root-x1-cross-signed.pem && cp isrg-root-x1-cross-signed.pem /etc/ssl/certs/

    - name: Build
      run: make ladder-config

    - name: Upload
      run: make upload
