name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: aiarena/arenaclient
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: apt-get install build-essential

    - name: Build
      run: make ladder-config

    - name: Upload
      run: make upload
